# Generated by Django 6.0.4 on 2026-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='codigo_recup',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
