# Generated by Django 6.0.4 on 2026-06-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadossolicpesquisa',
            old_name='doc_cart_vacin',
            new_name='outros',
        ),
    ]
