# Generated by Django 6.0.4 on 2026-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='acao_realizada',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='foto',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='gestor_resp',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='licenca_inst',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='retorno_comuni',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tabelateste',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tabelateste',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterModelTable(
            name='dadossolicpesquisa',
            table=None,
        ),
    ]
