# Generated by Django 6.0.7 on 2026-07-28 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossolicugai',
            name='id_public',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dadossolicugai',
            name='ativ_desenv',
            field=models.CharField(max_length=800, verbose_name='Atividades que irá desenvolver'),
        ),
    ]
