# Generated by Django 6.0.4 on 2026-06-12 14:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_doc_cart_vacin_dadossolicpesquisa_outros'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossolicpesquisa',
            name='licenca',
            field=models.FileField(default=1, upload_to=core.models.get_path_doc),
            preserve_default=False,
        ),
    ]
