# Generated by Django 6.0.7 on 2026-07-30 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dadossolicugai_id_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossolicpesquisa',
            name='id_public',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
