# Generated by Django 6.0.4 on 2026-04-30 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dadossolicpesquisa_acao_realizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='foto',
            field=models.CharField(choices=[('NA', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('INDEFERIDO', 'Indeferido'), ('ENCERRADO', 'Encerrado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='user_solic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='dadossolicpesquisa',
            table='solic_pesquisa',
        ),
    ]
