# Generated by Django 6.0.4 on 2026-05-04 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dadossolicpesquisa_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('ori_sexual', models.CharField(choices=[('mulher_trans', 'Mulher Trans'), ('homem_trans', 'Homem Trans'), ('mulher_cis', 'Mulher Cis'), ('homem_cis', 'Homem Cis'), ('outros', 'Outros')], max_length=12, verbose_name='Orientação sexual')),
                ('instituicao', models.CharField(max_length=80, verbose_name='Instituição')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('email_enviado', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('token_confirmacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
    ]
