# Generated by Django 6.0.4 on 2026-06-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dadossolicpesquisa_licenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadossolicpesquisa',
            name='licenca_inst',
        ),
    ]
