# Generated by Django 6.0.4 on 2026-05-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membroequipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabelaTeste',
        ),
    ]
