# Generated by Django 6.0.4 on 2026-06-12 15:51

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dadossolicpesquisa_licenca_inst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadossolicpesquisa',
            name='licenca',
        ),
        migrations.RemoveField(
            model_name='dadossolicpesquisa',
            name='outros',
        ),
        migrations.CreateModel(
            name='AnexExtraPesqLicenca',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('doc_url', models.FileField(upload_to=core.models.get_path_doc)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='core.dadossolicpesquisa')),
            ],
            options={
                'db_table': 'anex_pesq_licenca',
            },
        ),
        migrations.CreateModel(
            name='AnexExtraPesqOutros',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('doc_url', models.FileField(upload_to=core.models.get_path_doc)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outros_documentos', to='core.dadossolicpesquisa')),
            ],
            options={
                'db_table': 'anex_pesq_outros',
            },
        ),
    ]
