# Generated by Django 6.0.4 on 2026-05-13 14:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_tabelateste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ugai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('total_vagas', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ugai',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoUgais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_pessoas', models.PositiveIntegerField()),
                ('instituicao', models.CharField(blank=True, max_length=40, null=True, verbose_name='Instituição')),
                ('setor', models.CharField(blank=True, max_length=40, null=True)),
                ('cargo', models.CharField(blank=True, max_length=40, null=True)),
                ('ativ_desenv', models.CharField(max_length=200, verbose_name='Atividades que irá desenvolver')),
                ('publico_alvo', models.CharField(max_length=80, verbose_name='Público alvo')),
                ('recusa_motivo', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('INDEFERIDO', 'Indeferido'), ('ENCERRADO', 'Encerrado')], max_length=10)),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_final', models.DateField(default=django.utils.timezone.localdate)),
                ('user_solic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ugai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.ugai')),
            ],
            options={
                'db_table': 'solic_ugai',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipeUGAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(max_length=11)),
                ('cor_raca', models.CharField(choices=[('PRETA', 'Preta'), ('PARDA', 'Parda'), ('INDIGENA', 'Indigena'), ('AMARELA', 'Amarela'), ('BRANCA', 'Branca')], max_length=10)),
                ('genero', models.CharField(choices=[('mulher_trans', 'Mulher Trans'), ('homem_trans', 'Homem Trans'), ('mulher_cis', 'Mulher Cis'), ('homem_cis', 'Homem Cis'), ('outros', 'Outros')], max_length=12)),
                ('idade', models.IntegerField()),
                ('solicitacao_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao', to='core.solicitacaougais')),
            ],
            options={
                'db_table': 'equipe_ugai',
                'indexes': [models.Index(fields=['solicitacao_ref'], name='equipe_ugai_solicit_9f8f78_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacaougais',
            index=models.Index(fields=['ugai', 'data_inicio', 'data_final'], name='solic_ugai_ugai_id_ab0907_idx'),
        ),
    ]
