# Generated by Django 6.0.4 on 2026-05-19 13:53

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ugai_solicitacaougais_membroequipeugai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosRelFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=core.models.get_upload_path)),
                ('upado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arq_pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
    ]
